[meta]
version = 1
name = "dark-blue"
description = "Minimal dark-blue theme"
variant = "dark"
icon = ""

[colors.core]
background = "#0f1113"
foreground = "#b0b8c2"
secondary_background = "#0a0c10" 
border = "#0a0c10"   
accent = "#232936" 

[colors.accents]
blue = "#59C2FF"            
green = "#AAD94C"       
magenta = "#D2A6FF"          
orange = "#FF8F40"          
purple = "#c19eff"          
red = "#F07178"             
yellow = "#FFB454"         
cyan = "#95E6CB"          

[colors.list.item.selection]
background = { name = "#151923", opacity = 0.6 } 
secondary_background = "#151923"  

[colors.list.item.hover]
background = "#151923"  
