log_level = "warn"
outputs = { Targets = ["eDP-1"] }
position = "Top"

[modules]
left = [ [ "Workspaces" ] ]
center = [ ]
right = [  "Tray", "Settings", "Privacy", "Clock" ]

[clock]
format = "%X   %x"

[workspaces]
enable_workspace_filling = true
workspace_names = ["","","",""]

[settings]
battery_format = "Percentage"
lock_cmd = "swaylock"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
remove_wifi_more_cmd = true
remove_bluetooth_more_cmd = true
remove_airplane_btn = true
indicators = ["Battery",]
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
hibernate_cmd = "systemctl hibernate"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"

[appearance]
style = "Islands"
font_name = "JetBrainsMono Nerd Font"
opacity = 0.3
scale_factor = 0.9
primary_color = "#13151a"
success_color = "#13151a"
text_color = "#9aa6b5"
workspace_colors = [ "#13151a", "#13151a" ]
special_workspace_colors = [ "#9aa6b5", "#9aa6b5" ]

[appearance.menu]
opacity = 0.9
backdrop = 0

[appearance.danger_color]
base = "#13151a"
weak = "#13151a"

[appearance.background_color]
base = "#13151a"
weak = "#13151a"
strong = "#13151a"
text = "#13151a"

[appearance.secondary_color]
base = "#13151a"
