log_level = "warn"
outputs = { Targets = ["eDP-1"] }
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [ [ "Workspaces" ] ]
center = [ ]
right = [ [  "Tray", "Clock", "Privacy", "Settings" ] ]

[clock]
format = "%X   %x"

[workspaces]
enable_workspace_filling = true
workspace_names = ["  "]

[settings]
battery_format = "Percentage"
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"
remove_airplane_btn = true
remove_idle_btn = true
remove_power_btn = true
indicators = ["Audio", "Bluetooth", "Network", "Battery",]

[appearance]
style = "Islands"
font_name = "JetBrainsMono Nerd Font"
opacity = 0.8
scale_factor = 0.8
primary_color = "#171a1f"
success_color = "#9ece6a"
text_color = "#808a96"
workspace_colors = [ "#7aa2f7", "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.menu]
opacity = 0.7
backdrop = 0.3

[appearance.danger_color]
base = "#470919"
weak = "#171a1f"

[appearance.background_color]
base = "#06080a"
weak = "#171a1f"
strong = "#000000"
text = "#808a96"

[appearance.secondary_color]
base = "#06080a"
